apiVersion: apps/v1
kind: Deployment
metadata:
  name: movies
spec:
  replicas: 1
  selector:
    matchLabels:
      app: movies
  template:
    metadata:
      labels:
        app: movies
    spec:
      containers:
        - name: movies
          image: jhtoigo/rotten-potatoes:v10
          resources:
            requests:
              memory: "128Mi"
              cpu: "200m"
            limits:
              memory: "256Mi"
              cpu: "200m"
          ports:
          - containerPort: 5000
          envFrom:
          - configMapRef:
              name: configmap-movies
          env:           
            - name: MONGODB_USERNAME
              valueFrom:
                secretKeyRef:
                  key: MONGO_INITDB_ROOT_USERNAME
                  name: secret-mongodb

            - name: MONGODB_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: MONGO_INITDB_ROOT_PASSWORD
                  name: secret-mongodb